language: cpp
compiler:
  - gcc
  - clang
before_script:
  - mkdir ../build
  - cd ../build
script:
  - cmake ../381706-2_Kriukov_lab
  - make -j
#  - ./vector/vector
  - cd ./bin/
  -./vectortest
notifications:
  email: false
